name: tests
on:
  push:
      branches:
        - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run attw
    - run: npm run test
    strategy:
      matrix:
        node-version:
        - "20"
        - "22"

